version: '3'
services:
  backend:
    build: .
    container_name: 'arapgpserver'
    ports:
    - '3000:3000'
    depends_on:
    - db

  db:
    image: mongo
    container_name: 'arapgpdb'
    ports:
    - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'ljgtest'
      MONGO_INITDB_ROOT_USERNAME: 'ljg'
      MONGO_INITDB_ROOT_PASSWORD: 'ljg'
    restart: always
